import * as path from 'path';
import * as fs from 'fs';
import { Ports, DB_CONFIG } from '../types.js';
import { ensureDir, timestamp } from './utils.js';

/**
 * Generate the .env file for direct development (uses localhost)
 */
export function generateEnvFile(worktreePath: string, ports: Ports, worktreeId: string): void {
  const envPath = path.join(worktreePath, 'apps', 'api', '.env');
  const envDir = path.dirname(envPath);
  ensureDir(envDir);

  const content = `# Auto-generated by worktree setup
# Worktree ID: ${worktreeId}
# Generated: ${timestamp()}
# DO NOT COMMIT - use .env.example as template

# Server Ports
VITE_DEV_PORT=${ports.frontend}
API_PORT=${ports.backend}

# Database (running on host at port ${ports.database})
DATABASE_URL=postgresql://${DB_CONFIG.user}:${DB_CONFIG.password}@localhost:${ports.database}/${DB_CONFIG.database}?schema=public

# Development settings
NODE_ENV=development

# Auth bypass for worktree development (skips OAuth, uses a dev user)
VITE_AUTH_BYPASS=true
`;

  fs.writeFileSync(envPath, content);
  console.log(`Generated .env file at ${envPath}`);
}

/**
 * Generate the .env file for the web app (Vite needs VITE_ prefixed vars)
 */
export function generateWebEnvFile(worktreePath: string, ports: Ports, worktreeId: string): void {
  const envPath = path.join(worktreePath, 'apps', 'web', '.env');
  const envDir = path.dirname(envPath);
  ensureDir(envDir);

  const content = `# Auto-generated by worktree setup
# Worktree ID: ${worktreeId}
# Generated: ${timestamp()}
# DO NOT COMMIT

VITE_API_URL=http://localhost:${ports.backend}
VITE_DEV_PORT=${ports.frontend}
VITE_AUTH_BYPASS=true
`;

  fs.writeFileSync(envPath, content);
  console.log(`Generated web .env file at ${envPath}`);
}

/**
 * Generate the devcontainer.json for container development (uses host.docker.internal)
 */
export function generateDevcontainerJson(
  worktreePath: string,
  worktreeId: string,
  ports: Ports
): void {
  const devcontainerDir = path.join(worktreePath, '.devcontainer');
  const devcontainerPath = path.join(devcontainerDir, 'devcontainer.json');
  ensureDir(devcontainerDir);

  const config = {
    name: `InZone - ${worktreeId}`,
    dockerComposeFile: ['docker-compose.yml', 'docker-compose.worktree.yml'],
    service: 'app',
    workspaceFolder: '/InZone-App',
    customizations: {
      vscode: {
        extensions: [
          'anthropic.claude-code',
          'dbaeumer.vscode-eslint',
          'esbenp.prettier-vscode',
          'eamodio.gitlens',
          'Prisma.prisma',
        ],
        settings: {
          'editor.formatOnSave': true,
          'editor.defaultFormatter': 'esbenp.prettier-vscode',
          'editor.codeActionsOnSave': {
            'source.fixAll.eslint': 'explicit',
          },
          'terminal.integrated.defaultProfile.linux': 'zsh',
          'terminal.integrated.profiles.linux': {
            bash: {
              path: 'bash',
              icon: 'terminal-bash',
            },
            zsh: {
              path: 'zsh',
            },
          },
        },
      },
    },
    remoteUser: 'node',
    containerEnv: {
      NODE_OPTIONS: '--max-old-space-size=4096',
      CLAUDE_CONFIG_DIR: '/home/node/.claude',
      POWERLEVEL9K_DISABLE_GITSTATUS: 'true',
      DATABASE_URL: `postgresql://${DB_CONFIG.user}:${DB_CONFIG.password}@host.docker.internal:${ports.database}/${DB_CONFIG.database}?schema=public`,
      HOST_HOME: '${localEnv:HOME}',
      HOST_WORKSPACE: '${localWorkspaceFolder}',
      HOME: '/home/node',
      VITE_DEV_PORT: String(ports.frontend),
      API_PORT: String(ports.backend),
      VITE_API_URL: `http://localhost:${ports.backend}`,
      VITE_AUTH_BYPASS: 'true',
    },
    postCreateCommand:
      'sudo /usr/local/bin/fix-permissions.sh && pnpm install && pnpm --filter api db:generate',
    postStartCommand:
      'if [ -z "$CI" ]; then sudo /usr/local/bin/init-firewall.sh 2>/dev/null || true; fi && sudo mkdir -p "$HOST_HOME" && sudo ln -sf /home/node/.claude "$HOST_HOME/.claude" 2>/dev/null || true && sudo mkdir -p "$(dirname "$HOST_WORKSPACE")" && sudo ln -sf /InZone-App "$HOST_WORKSPACE" 2>/dev/null || true',
    waitFor: 'postStartCommand',
    features: {},
    forwardPorts: [ports.frontend, ports.backend, ports.database],
  };

  fs.writeFileSync(devcontainerPath, JSON.stringify(config, null, 2) + '\n');
  console.log(`Generated devcontainer.json at ${devcontainerPath}`);
}

/**
 * Generate the docker-compose.worktree.yml override (no db service - uses host DB)
 */
export function generateDockerComposeOverride(
  worktreePath: string,
  worktreeId: string,
  ports: Ports
): void {
  const devcontainerDir = path.join(worktreePath, '.devcontainer');
  const composePath = path.join(devcontainerDir, 'docker-compose.worktree.yml');
  ensureDir(devcontainerDir);

  const content = `# Auto-generated by worktree setup
# Worktree: ${worktreeId}
# Generated: ${timestamp()}
# DO NOT EDIT - regenerate with /worktree command

services:
  app:
    container_name: inzone-wt-${worktreeId}
    environment:
      - VITE_DEV_PORT=${ports.frontend}
      - API_PORT=${ports.backend}
      - VITE_API_URL=http://localhost:${ports.backend}
      - DATABASE_URL=postgresql://${DB_CONFIG.user}:${DB_CONFIG.password}@host.docker.internal:${ports.database}/${DB_CONFIG.database}?schema=public
      - VITE_AUTH_BYPASS=true
    ports:
      - "${ports.frontend}:${ports.frontend}"
      - "${ports.backend}:${ports.backend}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

# NOTE: Database runs on HOST at port ${ports.database}
# Container name: inzone-db-wt-${worktreeId}
# Started by worktree setup, not by this compose file
`;

  fs.writeFileSync(composePath, content);
  console.log(`Generated docker-compose.worktree.yml at ${composePath}`);
}

/**
 * Copy base devcontainer files (Dockerfile, docker-compose.yml, scripts)
 *
 * For docker-compose.yml, we strip environment variables that are worktree-specific
 * (DATABASE_URL, ports, etc.) so the worktree overlay is the sole source of truth.
 * This avoids relying on Docker Compose merge behavior for critical env vars.
 */
export function copyBaseDevcontainerFiles(worktreePath: string, mainRepoPath: string): void {
  const sourceDir = path.join(mainRepoPath, '.devcontainer');
  const targetDir = path.join(worktreePath, '.devcontainer');
  ensureDir(targetDir);

  // Files to copy verbatim
  const filesToCopy = [
    'Dockerfile',
    'fix-permissions.sh',
    'init-firewall.sh',
  ];

  for (const file of filesToCopy) {
    const sourcePath = path.join(sourceDir, file);
    const targetPath = path.join(targetDir, file);

    if (fs.existsSync(sourcePath)) {
      fs.copyFileSync(sourcePath, targetPath);
      if (file.endsWith('.sh')) {
        fs.chmodSync(targetPath, 0o755);
      }
    }
  }

  // Copy docker-compose.yml but strip worktree-specific env vars
  // so the worktree overlay is the sole source for DATABASE_URL, ports, etc.
  const composeSrc = path.join(sourceDir, 'docker-compose.yml');
  const composeDst = path.join(targetDir, 'docker-compose.yml');
  if (fs.existsSync(composeSrc)) {
    let content = fs.readFileSync(composeSrc, 'utf-8');
    // Remove lines that set env vars overridden by the worktree overlay
    const worktreeOverriddenVars = ['DATABASE_URL', 'VITE_DEV_PORT', 'API_PORT', 'VITE_AUTH_BYPASS'];
    for (const varName of worktreeOverriddenVars) {
      content = content.replace(new RegExp(`^\\s*-\\s*${varName}=.*\\n?`, 'gm'), '');
    }
    // Also remove comment lines referencing the stripped vars
    content = content.replace(/^\s*#.*Same DATABASE_URL.*\n?/gm, '');
    fs.writeFileSync(composeDst, content);
  }

  console.log(`Copied base devcontainer files to ${targetDir}`);
}

/**
 * Generate all configuration files for a worktree
 */
export function generateAllConfigs(
  worktreePath: string,
  worktreeId: string,
  ports: Ports,
  mainRepoPath: string
): void {
  // Copy base devcontainer files first
  copyBaseDevcontainerFiles(worktreePath, mainRepoPath);

  // Generate worktree-specific files
  generateEnvFile(worktreePath, ports, worktreeId);
  generateWebEnvFile(worktreePath, ports, worktreeId);
  generateDevcontainerJson(worktreePath, worktreeId, ports);
  generateDockerComposeOverride(worktreePath, worktreeId, ports);
}
